os: linux
dist: xenial
language: java

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  # chrome: stable

jdk:
  - openjdk12

before_install:
  # geckodriver 
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C $HOME/bin
  
  # chromedriver
  # - wget http://chromedriver.storage.googleapis.com/76.0.3809.126/chromedriver_linux64.zip
  # - unzip chromedriver_linux64.zip -d $HOME/bin
  # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - mvn clean test
  # - mvn clean test -D browser=chrome
